### ISSUE TITLE
希望能支持 离线下载

### ISSUE THREAD

**Issue by wssy001** [saltbo/zpan#100]
不知道作者是否打算支持支持Aria2 离线下载

**Comment by saltbo** [comment]
最早是有的，后来想想我们的初衷是做不限速的网盘，意味着zpan部署在一个低带宽的服务器上，所以支持Aria2下载也没啥用。

但是我最近又想，可能也可以把zpan部署在自己家的nas上，这个时候Aria2就有用了。我还在考虑中

**Comment by wssy001** [comment]
是这样的，像我租的服务器都是按流量计费，而且不少服务器都是只算出站流量。这时候你就可以用大带宽下载文件，然后通过内网传至OSS。顺便插个请求，像阿里 ，如果你的OSS和ECS是同个地域，ECS的文件可以走内网传输到OSS，内网出入站流量免费。我试用了一下zpan，好像并没有做内网endpoint的适配，(但可能是我使用有误)，望作者能考虑一二。

**Comment by saltbo** [comment]
按流量计费下载带宽不限制？ 那就值得加上Aria2了。  #14

**Comment by saltbo** [comment]
关于内网Endpoint，我们并没有限制Endpoint的使用，都是自己填入的，你填内网就好。但是v1.6之前填内网会影响下载，从v1.6开始可以再填一个自有域名绑定外网就可以用了。
