### ISSUE TITLE
S3不支持中国区

### ISSUE THREAD

**Issue by DingKuiqing** [saltbo/zpan#101]
接入点：https://s3.cn-north-1.amazonaws.com.cn或https://s3.cn-northwest-1.amazonaws.com.cn
提示AuthorizationHeaderMalformed: The authorization header is malformed; the region 'auto' is wrong; expecting 'cn-north-1' status code: 400, request id: K38G3FED2Q54S29S, host id: fo8La5e/h+DYukbnlSr1+fZAPek0ZfcHbaGzIvCWSZIDS2c6KgO3TwSgC3pftgkhBKRUy91BDSI=

**Comment by DingKuiqing** [comment]
麻烦作者酌情修复
需要提供账户测试可以联系我
非常感谢

**Comment by saltbo** [comment]
这个问题我还真没发现，等我测一下。当初为了简便就直接用了auto，这个auto的覆盖范围可能有限

**Comment by saltbo** [comment]
fixed on https://github.com/saltbo/zpan/commit/0db0d1462e69fb3cb793c105b9a2922d74314772
