### ISSUE TITLE
云存储接口希望能加入一些便捷功能

### ISSUE THREAD

**Issue by recdown** [saltbo/zpan#103]
云存储接口希望能加入启用停用的功能,直接拖拽上传,如果可以指定用户使用某一接口就更好了.

**Comment by saltbo** [comment]
> 云存储接口希望能加入启用停用的功能
指的是停用已经添加上的云存储么？ 

> 直接拖拽上传
现在就是支持的

>如果可以指定用户使用某一接口就更好了
不明白什么意思

**Comment by recdown** [comment]
> 云存储接口希望能加入启用停用的功能
指的是停用已经添加上的云存储

> 如果可以指定用户使用某一接口就更好了
比如接入了全部云存储。但是设置设置用户只可以用其中一个

**Comment by saltbo** [comment]
这两个功能后续会加入

**Comment by saltbo** [comment]
禁用云存储已支持，设置用户只可以用其中一个云存储功能依赖用户组，暂无计划支持用户组，所以先推迟

**Comment by saltbo** [comment]
#96
