### ISSUE TITLE
回收站删除报错

### ISSUE THREAD

**Issue by recdown** [saltbo/zpan#107]
![image](https://user-images.githubusercontent.com/44447180/121113270-55569100-c844-11eb-9dee-801c9a2fd9f9.png)

**Comment by recdown** [comment]
清空回收站提示
![image](https://user-images.githubusercontent.com/44447180/121113717-12e18400-c845-11eb-944e-cc38893f2f99.png)

**Comment by saltbo** [comment]
用的哪个版本？用的哪个云存储？ 接入点写的啥用的啥

**Comment by recdown** [comment]
![image](https://user-images.githubusercontent.com/44447180/121114978-14ac4700-c847-11eb-9b7c-1be49e8ee983.png)
![image](https://user-images.githubusercontent.com/44447180/121115014-2261cc80-c847-11eb-81f1-2b5609523cfa.png)
七牛云，版本应该是v1.4.1

**Comment by recdown** [comment]
![Uploading image.png…]()

**Comment by recdown** [comment]
![Uploading image.png…]()

**Comment by saltbo** [comment]
你自有域名解析到哪儿了 先不要用自有域名试下

**Comment by recdown** [comment]
自有域名解析到CNAME了
![image](https://user-images.githubusercontent.com/44447180/121125571-5c3bce80-c859-11eb-9ad5-87030261341a.png)

**Comment by recdown** [comment]
可以上传,但是不能删除,
![image](https://user-images.githubusercontent.com/44447180/121127743-d28e0000-c85c-11eb-848e-0e03bc4171f2.png)
七牛云那边说是没有传参

**Comment by saltbo** [comment]
不能解析到七牛的地址 得解析到s3域名 七牛自己的域名不兼容s3协议
