### ISSUE TITLE
文件上传删除后，存在命名问题

### ISSUE THREAD

**Issue by recdown** [saltbo/zpan#110]
文件上传删除后，再上传同样文件，会自动修改标题，改回原标题会提示已有同名文件，实际已删除

**Comment by saltbo** [comment]
你运行的是最新版本么 我测试了一下没发现有这个问题啊

**Comment by recdown** [comment]
你上传一个文件，比如名字是测试文件1号
传好删掉后
再次上传
想要命名为测试文件1号
会提示已存在同名文件

**Comment by saltbo** [comment]
我试过了 没有复现 所以需要你确认下是否是最新版本

**Comment by saltbo** [comment]
http://zpan.saltbo.cn
演示账号demo 密码demo 你在这上面试试呢

**Comment by recdown** [comment]
invalid password

**Comment by saltbo** [comment]
你太晚了，这个演示账号总是被改。你在群里么，群里聊

**Comment by saltbo** [comment]
先关掉了，有问题再反馈
