### ISSUE TITLE
服务开启后立即退出 退出代码203

### ISSUE THREAD

**Issue by yf31** [saltbo/zpan#115]
<img width="907" alt="截屏2021-07-11 下午12 07 40" src="https://user-images.githubusercontent.com/74579592/125182487-f0c29380-e240-11eb-92ac-08443c95abd2.png">

**Comment by yf31** [comment]
centOS 7.6 和 8 都是这样

**Comment by saltbo** [comment]
journalctl -xe -u zpan -f 看下详细日志

**Comment by saltbo** [comment]
先关掉了，有问题再反馈
