### ISSUE TITLE
希望能增加的功能

### ISSUE THREAD

**Issue by ZHlovecat** [saltbo/zpan#118]
1、支持更改头像
2、既然用到了云存储，希望能够实现常见格式的文档预览功能（比如对接腾讯云cos服务的，可以调用腾讯云的数据万象功能实现文件的html预览）（cloudreve调用的office的文档在线预览的接口），希望咱们这个盘这个功能也可以有。
3、增加网页自定义图标的功能
4、增加暗夜模式

**Comment by saltbo** [comment]
1. 头像下个版本会支持
2. 目前已经支持office文件预览，其他如pdf、文本等下个版本也会支持
3. 自定义图标没计划开放
4. 暗夜模式后面也会支持，但优先级较低

**Comment by saltbo** [comment]
支持设置头像存储，设置后可以上传头像到该存储地址
