### ISSUE TITLE
想问一下，如何升级新版本呢？

### ISSUE THREAD

**Issue by ZHlovecat** [saltbo/zpan#124]
之前是直接通过服务器直接部署的，对于Zpan新的版本出来了，通过不同方式安装的小伙伴，如何升级，体验新的功能呢？

**Comment by saltbo** [comment]
重新执行一下那个安装命令就行了；如果是docker运行的，执行docker pull更新镜像，然后docker restart就好了

**Comment by ZHlovecat** [comment]
> 重新执行一下那个安装命令就行了；如果是docker运行的，执行docker pull更新镜像，然后docker restart就好了

好的，谢谢

**Comment by ZHlovecat** [comment]
我重新执行了“curl -sSf https://dl.saltbo.cn/install.sh | sh -s zpan”这个安装命令后，刷新了，为啥一点变化也没有呢？我问题出在哪里了啊？

**Comment by ZHlovecat** [comment]
> 重新执行一下那个安装命令就行了；如果是docker运行的，执行docker pull更新镜像，然后docker restart就好了

我重新执行了“curl -sSf https://dl.saltbo.cn/install.sh | sh -s zpan”这个安装命令后，刷新了，为啥一点变化也没有呢？我问题出在哪里了啊？看了，没有用啊，还是之前的版本！

**Comment by saltbo** [comment]
systemctl update zpan
