### ISSUE TITLE
即使网站是https分析链接生成的也是http

### ISSUE THREAD

**Issue by recdown** [saltbo/zpan#130]
即使网站是https分析链接生成的也是http

**Comment by recdown** [comment]
复制链接时，如果有密码。不会复制密码

**Comment by saltbo** [comment]
> 即使网站是https分析链接生成的也是http

自有域名设置带上https://  就有了

**Comment by saltbo** [comment]
> 复制链接时，如果有密码。不会复制密码

我想的是复制出来能直接访问。 不过可能真实的场景是复制出来分享给别人，那就需要把密码一起复制上了。
