### ISSUE TITLE
armv7 support?

### ISSUE THREAD

**Issue by IMZCC** [saltbo/zpan#132]
armv7 support?
I need it.

**Comment by saltbo** [comment]
already supported.

but, the install.sh not support download the zpan-linux-arm64.tar.gz, you can try to manual download it from the Release page

https://github.com/saltbo/zpan/releases/tag/v1.6.4

If it doesn't work, please continue your feedback here.

**Comment by IMZCC** [comment]
I didn't find armv7, only arm64, but it can't be used on my device.
![image](https://user-images.githubusercontent.com/25655983/133877666-e83c71be-091a-440b-a10c-ebf7204a94f2.png)

![image](https://user-images.githubusercontent.com/25655983/133877678-4041c1db-6410-47ee-8a93-30b1cf6a8482.png)

**Comment by saltbo** [comment]
armv6l default, In the next version, I will build an armv7l artifact.

**Comment by IMZCC** [comment]
Ok, i will look forward to it.
