### ISSUE TITLE
是否不支持arm64架构系统？

### ISSUE THREAD

**Issue by kun775** [saltbo/zpan#133]
![image](https://user-images.githubusercontent.com/12853372/134444242-8f45b5d1-34c1-4b15-a4bb-6117e9eff1c9.png)
我是打算安装在树莓派上，系统是openfans，基于Debian，64位系统

**Comment by saltbo** [comment]
v1.6.x版本已经支持了，但是一键安装脚本好像没支持。可以先手动下载解压使用
