### ISSUE TITLE
service zpan start 8222没有跑起来

### ISSUE THREAD

**Issue by xielk** [saltbo/zpan#153]
日志如下
-- The start-up result is done.
Jan 14 15:14:06 localhost.localdomain zpan[22439]: time="2022-01-14T02:14:06-05:00" level=warning msg="grbac abandoned the periodic loader because loadInterval is less than 0"
Jan 14 15:14:06 localhost.localdomain zpan[22439]: 2022/01/14 02:14:06 [rest server listen at :8222]
Jan 14 15:16:41 localhost.localdomain systemd[1]: Stopping Zpan...
-- Subject: Unit zpan.service has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zpan.service has begun shutting down.
Jan 14 15:16:41 localhost.localdomain zpan[22439]: 2022/01/14 02:16:41 Shutdown Server ...
Jan 14 15:16:41 localhost.localdomain zpan[22439]: 2022/01/14 02:16:41 [http server exited.]
Jan 14 15:16:41 localhost.localdomain systemd[1]: Stopped Zpan.
-- Subject: Unit zpan.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

**Comment by saltbo** [comment]
journalctl -u zpan查看日志

**Comment by xielk** [comment]
[root@localhost ~]# journalctl -u zpan
-- Logs begin at Mon 2022-01-10 23:48:23 CST, end at Fri 2022-01-14 22:04:04 CST. --
Jan 14 14:44:06 localhost.localdomain systemd[1]: Started Zpan.
Jan 14 14:44:06 localhost.localdomain zpan[22280]: time="2022-01-14T01:44:06-05:00" level=warning
Jan 14 14:44:06 localhost.localdomain zpan[22280]: 2022/01/14 01:44:06 [rest server listen at :82
Jan 14 14:48:40 localhost.localdomain systemd[1]: Stopping Zpan...
Jan 14 14:48:40 localhost.localdomain zpan[22280]: 2022/01/14 01:48:40 Shutdown Server ...
Jan 14 14:48:40 localhost.localdomain systemd[1]: Stopped Zpan.
Jan 14 14:48:40 localhost.localdomain zpan[22280]: 2022/01/14 01:48:40 [http server exited.]
Jan 14 14:48:40 localhost.localdomain systemd[1]: Started Zpan.
Jan 14 14:48:41 localhost.localdomain zpan[22331]: time="2022-01-14T01:48:41-05:00" level=warning
Jan 14 14:48:41 localhost.localdomain zpan[22331]: 2022/01/14 01:48:41 [rest server listen at :82
Jan 14 15:14:06 localhost.localdomain systemd[1]: Stopping Zpan...
Jan 14 15:14:06 localhost.localdomain zpan[22331]: 2022/01/14 02:14:06 Shutdown Server ...
Jan 14 15:14:06 localhost.localdomain systemd[1]: Stopped Zpan.
Jan 14 15:14:06 localhost.localdomain zpan[22331]: 2022/01/14 02:14:06 [http server exited.]
Jan 14 15:14:06 localhost.localdomain systemd[1]: Started Zpan.
Jan 14 15:14:06 localhost.localdomain zpan[22439]: time="2022-01-14T02:14:06-05:00" level=warning
Jan 14 15:14:06 localhost.localdomain zpan[22439]: 2022/01/14 02:14:06 [rest server listen at :82
Jan 14 15:16:41 localhost.localdomain systemd[1]: Stopping Zpan...
Jan 14 15:16:41 localhost.localdomain zpan[22439]: 2022/01/14 02:16:41 Shutdown Server ...
Jan 14 15:16:41 localhost.localdomain zpan[22439]: 2022/01/14 02:16:41 [http server exited.]
Jan 14 15:16:41 localhost.localdomain systemd[1]: Stopped Zpan.
Jan 14 15:16:41 localhost.localdomain systemd[1]: Started Zpan.
Jan 14 15:16:41 localhost.localdomain zpan[22472]: time="2022-01-14T15:16:41+08:00" level=warning
Jan 14 15:16:41 localhost.localdomain zpan[22472]: 2022/01/14 15:16:41 [rest server listen at :82
Jan 14 22:04:04 localhost.localdomain systemd[1]: Stopping Zpan...
Jan 14 22:04:04 localhost.localdomain zpan[22472]: 2022/01/14 22:04:04 Shutdown Server ...
Jan 14 22:04:04 localhost.localdomain zpan[22472]: 2022/01/14 22:04:04 [http server exited.]
Jan 14 22:04:04 localhost.localdomain systemd[1]: Stopped Zpan.
Jan 14 22:04:04 localhost.localdomain systemd[1]: Started Zpan.
Jan 14 22:04:04 localhost.localdomain zpan[1834]: time="2022-01-14T22:04:04+08:00" level=warning 
Jan 14 22:04:04 localhost.localdomain zpan[1834]: 2022/01/14 22:04:04 [rest server listen at :822
[root@localhost ~]# nc -v 127.0.0.1 8222
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:8222.

**Comment by saltbo** [comment]
没有报错

Jan 14 22:04:04 localhost.localdomain systemd[1]: Stopping Zpan...  这看起来是被什么程序stop了

**Comment by xielk** [comment]
[root@localhost ~]# netstat -na | grep 8222
tcp6       0      0 :::8222                 :::*                    LISTEN

**Comment by saltbo** [comment]
这就启动成功了啊，显示tcp6跟你内核配置有关，正常来说是不影响的
