### ISSUE TITLE
arm64 平台上 使用出现错误

### ISSUE THREAD

**Issue by jhalx** [saltbo/zpan#162]
错误具体内容：
2022/05/18 14:25:26 /home/runner/work/zpan/zpan/internal/pkg/gormutil/gorm.go:54
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
[GIN] 2022/05/18 - 14:25:26 | 500 |    1.533231ms |  192.168.247.95 | PUT      "/api/system/database"
Error #01: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

似乎是因为交叉编译的问题

**Comment by saltbo** [comment]
你这个是在哪里运行的啊 什么系统？

**Comment by jhalx** [comment]
> 你这个是在哪里运行的啊 什么系统？

android arm64 平台 debian系统

**Comment by saltbo** [comment]
这是个服务端程序啊  为啥要在Android上运行 😅

**Comment by jhalx** [comment]
> 这是个服务端程序啊 为啥要在Android上运行 😅

其实跟树莓派之类的差不多 就是服务端。。。

**Comment by saltbo** [comment]
@jhalx 我没试过这种 但是为了支持sqlite 所以依赖cgo 之前Windows有类似问题 我一直没时间解决它

**Comment by jhalx** [comment]
> @jhalx 我没试过这种 但是为了支持sqlite 所以依赖cgo 之前Windows有类似问题 我一直没时间解决它

我试试 解决了 告诉你

**Comment by jhalx** [comment]
> @jhalx 我没试过这种 但是为了支持sqlite 所以依赖cgo 之前Windows有类似问题 我一直没时间解决它

我成功编译了 但是运行起来程序无法正常启动？ 我也不知道为什么

**Comment by jhalx** [comment]
我是直接clone 的master分支

**Comment by saltbo** [comment]
@jhalx 不要用master分支 master分支正在开发中 可以用release_v1.6那个分支

**Comment by jhalx** [comment]
> @jhalx 不要用master分支 master分支正在开发中 可以用release_v1.6那个分支

好的 我明天有空再试试
