### ISSUE TITLE
安装时提示driver: bad connection

### ISSUE THREAD

**Issue by YoghurtGuy** [saltbo/zpan#163]
如题，是我的dsn设置不正确吗

**Comment by YoghurtGuy** [comment]
已解决，但是发现白话文教程中的错误
![image](https://user-images.githubusercontent.com/41856917/169255149-4454df88-ad84-4e52-9916-024e3c2235ae.png)
用户名后面是密码，不是数据库名

**Comment by nanmaowang** [comment]
数据库地址是127.0.0.1:3306吗   我安装提示 
dial tcp 127.0.0.1:3306: connect: connection refused

**Comment by saltbo** [comment]
> 数据库地址是127.0.0.1:3306吗 我安装提示 dial tcp 127.0.0.1:3306: connect: connection refused

要看你是什么安装方式，如果是zpan在docker里，数据库又不是在docker里就不能用127.0.0.1了。

两个解决方案：
1. docker启动zpan时使用host模式，就可以用127.0.0.1了
2. 连接地址改为docker0的ip地址，可以在宿主机上ifconfig查看
