### ISSUE TITLE
请问用户密码在md5时，没有加盐吗？

### ISSUE THREAD

**Issue by huobazi** [saltbo/zpan#166]
我简单看了下，好像是没有加盐的。

https://github.com/saltbo/zpan/blob/d678464302c3ce72875e4ed179166b461ceab90e/internal/app/service/user.go#L41

https://github.com/saltbo/zpan/blob/d678464302c3ce72875e4ed179166b461ceab90e/internal/app/service/user.go#L90

**Comment by saltbo** [comment]
用户及登录这部分只是一个简单的实现，很多问题都没考虑。因为之前已经做过很多遍类似的逻辑了，我觉得重复做这玩意儿没啥意思。

我一直在找一个开源的用户系统，最近发现logto已经比较成熟了，后面可能会考虑直接接入logto。 https://github.com/logto-io/logto
