### ISSUE TITLE
项目部署成功，上传文件失败，调试不成功

### ISSUE THREAD

**Issue by XiaoPengBei** [saltbo/zpan#169]
**问题描述**：
我是开发使用MacbookPro Intel版，本地镜像部署运行一直失败。提示 `exec ./zpan: exec format error`，挣扎了无果。
于是将项目传到云服务器上面通过镜像部署运行成功，但是上传文件一直失败，接口也没有报错信息。所以准备调试项目，但是一直失败。

**错误信息**：
`error layer=rpc rpc:invalid character 'G' looking for beginning of value`

**调试步骤**：
1、dlv 安装到远程服务器上

```shell
$ git clone https://github.com/go-delve/delve
$ cd delve
$ go install github.com/go-delve/delve/cmd/dlv
```

2、服务器上编译项目
```shell 
go build -gcflags="all=-N -l" -o zpan main.go
```

3、服务器上开启端口监听
```shell
dlv --listen=:8222 --headless=true --api-version=2 --accept-multiclient --check-go-version=false  exec ./zpan server
```

4、本地Goland开启debug模式
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/33892330/184537328-c9661fe5-b74a-4b18-ad64-621f2f9de80a.png">

5、访问项目，请求失败
<img width="843" alt="image" src="https://user-images.githubusercontent.com/33892330/184537371-f0d6513a-19c5-44e5-a8c7-451c1de4e0a7.png">

请问大家有没有遇到这种情况，我这问题出在哪里或者大家是怎么调试的？

谢谢

**Comment by saltbo** [comment]
@XiaoPengBei 你是怎么安装的，使用安装脚本的话目前只支持amd64，如果你的mbp是intel的，那是不应该出现`exec format error`的。除非你是M1的mbp； 如果是你M！

**Comment by XiaoPengBei** [comment]
> @XiaoPengBei 你是怎么安装的，使用安装脚本的话目前只支持amd64，如果你的mbp是intel的，那是不应该出现`exec format error`的。除非你是M1的mbp； 如果是你M1的MBP，如果是M1的话，目前需要手动下载。 https://github.com/saltbo/zpan/releases
> 
> 没用过dlv，但看报错error layer=rpc rpc:invalid character 'G' looking for beginning of value是说没有正常返回可以解析的数据。不知道你哪里配置有问题

感谢回复。

安装脚本是指 https://zpan.space/#/getting-started?id=linux 吗？我不是使用这个操作的。

我是下载项目源代码后，直接自行`go build -o zpan main.go` 后，运行 `./zpan server`的。

因为我是想基于该项目进行二次开发，遇到上传文件不上去的问题，临时找到使用dlv的。不知道你是怎么调试该项目的？

**Comment by saltbo** [comment]
@XiaoPengBei 本地go build更不可能出现那个错误了啊 我就用goland里的调试

**Comment by XiaoPengBei** [comment]
1. 本地mbp go build 后运行异常，提示 `exec ./zpan: exec format error`
1. 云服务器centos go build 后运行正常，但上传文件失败

我也尝试本地debug模式运行来着，但是启动后就退出了，是哪里配置不对吗？😂
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/33892330/184584909-63e75e71-e1c9-456a-b66e-7914666389d3.png">

<img width="714" alt="image" src="https://user-images.githubusercontent.com/33892330/184584981-a2645f7e-5a2a-4339-81b3-7045573680fe.png">

**Comment by saltbo** [comment]
@XiaoPengBei file ./zpan看下

**Comment by XiaoPengBei** [comment]
@saltbo  如下图
![image](https://user-images.githubusercontent.com/33892330/184661665-b7378a48-4a8f-4085-a255-4b83f5eb5793.png)

**Comment by saltbo** [comment]
你docker run也报那个错误？ 诡异了。。
