### ISSUE TITLE
MinIO云存储不能带端口吗？

### ISSUE THREAD

**Issue by wwf99** [saltbo/zpan#182]
部署zpan
docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora

部署minio
docker run --name minio \
-p 8900:9000 \
-p 8990:9090 \
-d --restart=always \
-e "MINIO_DOMAIN=xxx.xxx.com:8900" \
-e "MINIO_ROOT_USER=admin" \
-e "MINIO_ROOT_PASSWORD=12345678" \
-v /usr/local/minio/data:/data \
-v /usr/local/minio/config:/root/.minio \
minio/minio server /data \
--console-address '0.0.0.0:9090'

创建存储
![image](https://github.com/saltbo/zpan/assets/36400629/d87d41be-e2c7-462d-a7e4-efe21d7e037b)

上传失败
![image](https://github.com/saltbo/zpan/assets/36400629/b0311978-59e4-41b5-b5dc-0f93155bb6cc)

**Comment by saltbo** [comment]
https://zpan.space/#/faq
