### ISSUE TITLE
Do you need the OneDrive or the GoogleDrive?

### ISSUE THREAD

**Issue by saltbo** [saltbo/zpan#22]
This is a user survey, please tell me your reason.

**Comment by mikulo** [comment]
google drive
onedrive的程序已经非常多了，但是google drive的网盘管理程序几乎没有，而且onedrive api相当于google drive来说太容易爆炸了

**Comment by saltbo** [comment]
I thought about GoogleDrive, it’s really not so good because of the GFW

If we use the server transfer method, then you have to deploy outside the wall while ensuring that your own server is not blocked by the GFW.

If you use a straight-chain approach, you will require both the deployment server and your own computer to overcome the GFW

**Comment by Creling** [comment]
As for me, I don't think it is necessary to support OneDrive or Google Drive.
Zpan, instead of a file list like h5ai, is a cloud drive, which focus on share some particular files with others but not share all files in your drive.  So, if we want to share files stored in our OneDrive, why don't we use OneDrive directly that support more ACL options?

**Comment by Creling** [comment]
In my opinion, compare with OneDrive, priority should be given to other **normal** object storage backend like Upyun and B2. No serious user will use OneDrive as a backend for we all know from where those ```cheap``` OneDrive account comes and the risks those account faces.

**Comment by saltbo** [comment]
@Creling At the moment, I think so too.

**Comment by dzhl** [comment]
希望支持onedrive，毕竟其他几款用的人还是没有太多

**Comment by uxiaohan** [comment]
大部分服务器存储空间有限，相对来说，现在用onedrive的用户非常之多，还是希望添加的！支持作者！

**Comment by maplefz** [comment]
希望能增加onedrive国际版以及世纪互联的支持，找了很多网盘应用，就这个网盘界面很满意，希望能增加更多的挂载网盘

**Comment by saltbo** [comment]
@maplefz 能说说你的使用场景么 我上面已经说过了 使用od gd都需要把zpan部署在境外 有那功夫 解决翻墙问题就好了 没必要套娃

**Comment by uxiaohan** [comment]
> @maplefz 能说说你的使用场景么 我上面已经说过了 使用od gd都需要把zpan部署在境外 有那功夫 解决翻墙问题就好了 没必要套娃

od国内速度还是可以的，而且教育版存储空间非常可观且免费。

**Comment by maplefz** [comment]
> @maplefz 能说说你的使用场景么 我上面已经说过了 使用od gd都需要把zpan部署在境外 有那功夫 解决翻墙问题就好了 没必要套娃

我使用的是世纪互联，有时候需要共享一些大文件给别人，能做到网盘挂载的话就不用给整个账号别人了，而且也可以不用每分享一个文件就在世纪互联里单独创建分享链接

**Comment by saltbo** [comment]
@maplefz zpan的分享逻辑跟od是一样的啊，一样需要创建分享链接。 除非使用外链盘，但是如果你只是想用外链盘，可以使用zfile
