### ISSUE TITLE
Support folder upload

### ISSUE THREAD

**Issue by Towdium** [saltbo/zpan#31]
Now the web page only accepts upload files, but does not accept folders.

**Comment by saltbo** [comment]
Yes, we don't support upload a folder now, we support upload a single file or multi-files.

The reason for not supporting is browser limitation, upload a folder is only supported by the Chrome browser, so we think to implement it is not worth it.

**Comment by saltbo** [comment]
Could expect the WebDAV And the Native-APP #19 https://github.com/saltbo/zpan/projects/2#column-10762171

**Comment by Towdium** [comment]
That's reasonable. What I have noticed is Cloudreve accepts folder upload, but possibly by uploading files one by one. Personally speaking, WebDAV is good enough to me in most of the cases. Feel free to close the issue if it's not planned.

**Comment by saltbo** [comment]
If we have time, we will consider implementing it, thanks for your suggestion.
