### ISSUE TITLE
don't allow move the folder into itself

### ISSUE THREAD

**Issue by saltbo** [saltbo/zpan#4]
This is a bug, should fix it early.

**Comment by holicc** [comment]
i'll fix it

**Comment by saltbo** [comment]
The judgment conditions are not strict #26 

eg:
- test
   - test2
- test2

I want to move the /test2 into the /test/test2, That judgment condition is unreasonable.

**Comment by saltbo** [comment]
I think we should judge the parent whether the directory exists，this problem can be solved by filtering out itself in the query condition.

Don't use the `name`, you could use the `alias`

**Comment by holicc** [comment]
> The judgment conditions are not strict #26
> 
> eg:
> 
> * test
>   
>   * test2
> * test2
> 
> I want to move the /test2 into the /test/test2, That judgment condition is unreasonable.
> 
> @holicc

if the  `test2` both  have a same file  `1.txt` , what' should we do?

**Comment by saltbo** [comment]
Yes, this situation also needs to be prevented.

**Comment by saltbo** [comment]
The copy feature maybe has the same problem

**Comment by holicc** [comment]
> Yes, this situation also needs to be prevented.

this situation need to compare file with `name` 

> I think we should judge the parent whether the directory exists，this problem can be solved by filtering out itself in the query condition.
> 
> Don't use the `name`, you could use the `alias`

To judge the parent whether the directory exists , i think we could use `alias` instead of `dir` as request parameter . Cause i can use `alias`  tell whether the directory exists and avoid the directory move to itself , also find children directories . so that we can resolve situation which mentioned before.

**Comment by saltbo** [comment]
My fault, you can use the `service.MatterParentExist()` and `service.MatterExist()` directly
