### ISSUE TITLE
希望文档详细一些

### ISSUE THREAD

**Issue by riba2534** [saltbo/zpan#41]
直接按照说明文档搭建，会产生跨域问题，请问这个怎么解决。

**Comment by saltbo** [comment]
文档还没来得及完善，你用的哪个平台？ 直接搜他们的文档怎么设置跨域

**Comment by Fcatme** [comment]
有望推出APP客户端啥的吗= =

**Comment by saltbo** [comment]
> 有望推出APP客户端啥的吗= =

短期内没有计划 等功能稳定后会考虑退出的，因为WEBDav不能直传，与我们的定位不太相符
