### ISSUE TITLE
注册显示ticket required

### ISSUE THREAD

**Issue by SimonHunag** [saltbo/zpan#43]
你好，zpan在注册的时候需要邀请码，请问这样邀请码是哪里来的？

**Comment by saltbo** [comment]
zpan.saltbo.cn仅提供一个演示账号，我们不提供注册服务，建议您试用后进行自建。

演示账号密码均为demo

**Comment by SimonHunag** [comment]
我已经在本地已经运行起来了，现在图片上传的时候没有报错，但是就是上传不上去，哪里可以到错误日志？

**Comment by SimonHunag** [comment]
![image](https://user-images.githubusercontent.com/26128315/95989808-53773200-0e5d-11eb-9ecf-cfebeba8a52e.png)
修改之后 也没有生效

**Comment by saltbo** [comment]
> 我已经在本地已经运行起来了，现在图片上传的时候没有报错，但是就是上传不上去，哪里可以到错误日志？

在运行日志里可以看到。您可能需要修改配置文件中的provider，改成您自己的云存储配置。

**Comment by saltbo** [comment]
> ![image](https://user-images.githubusercontent.com/26128315/95989808-53773200-0e5d-11eb-9ecf-cfebeba8a52e.png)
> 修改之后 也没有生效

这个是用户创建时的默认大小，对于管理员账户来说初次启动之后就不能改了。您可以删除数据库文件后重新启动就会生效了。

另外，请关注即将发布的v1.4版本，将会支持在后台调整用户的配额限制

**Comment by SimonHunag** [comment]
> > 我已经在本地已经运行起来了，现在图片上传的时候没有报错，但是就是上传不上去，哪里可以到错误日志？
> 
> 在运行日志里可以看到。您可能需要修改配置文件中的provider，改成您自己的云存储配置。

![image](https://user-images.githubusercontent.com/26128315/95998030-06985900-0e67-11eb-89a5-93546bb296c7.png)
已经改过了

**Comment by SimonHunag** [comment]
你文档里面微信群二维码过期了，你能重新发我下吗

**Comment by saltbo** [comment]
加我微信吧 跟GitHub用户名一样
