### ISSUE TITLE
管理员默认账号和无法上传

### ISSUE THREAD

**Issue by lanzeweie** [saltbo/zpan#49]
比较小白，按教程搭建后，配置MySQL数据库正常运行，但是在网盘页面无法上传文件，进度是零，关闭后也没有文件出现
后台显示[GIN] 2020/11/03 - 18:36:58 | 200 |    6.427825ms |  18.163.206.111 | POST     "/api/files"
可以新建文件夹
管理员默认账号密码输出位置没有找到
望解答

**Comment by saltbo** [comment]
打开配置文件填写自己的存储配置即可

**Comment by saltbo** [comment]
哦对 还有CORS的问题 参考文档到云平台上配置

**Comment by lanzeweie** [comment]
感谢你的热心回答，请问有本地存储功能嘛？

**Comment by saltbo** [comment]
没有 我们也不打算支持本地存储 如果你想用本地存储 可以使用MinIO搭建类似云存储的服务与ZPan配合使用

**Comment by lanzeweie** [comment]
感谢您的回复，谢谢
