### ISSUE TITLE
我用群晖docker搭了一个，但是不会改配置文件

### ISSUE THREAD

**Issue by fanxinghaoyue0** [saltbo/zpan#51]
请问怎么访问docker里的配置文件呢

**Comment by saltbo** [comment]
确实，这是一个问题。目前比较好的办法是在宿主机新建一个配置文件，然后把这个配置文件挂载到容器里去。&nbsp;



                                                                                                                                              Ambor
                 about.me/saltbo                                       
      



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saltbo/zpan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 下午2:21
收件人:&nbsp;"saltbo/zpan"<zpan@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[saltbo/zpan] 我用群晖docker搭了一个，但是不会改配置文件 (#51)





 
请问怎么访问docker里的配置文件呢

**Comment by fanxinghaoyue0** [comment]
> 确实，这是一个问题。目前比较好的办法是在宿主机新建一个配置文件，然后把这个配置文件挂载到容器里去。&nbsp; Ambor about.me/saltbo &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "saltbo/zpan" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月9日(星期一) 下午2:21 收件人:&nbsp;"saltbo/zpan"<zpan@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[saltbo/zpan] 我用群晖docker搭了一个，但是不会改配置文件 (#51) 请问怎么访问docker里的配置文件呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我用vps搭建的访问不了 就只有docker的可以 请教有没有挂载或者直接修改镜像内配置文件的方法，我会修改但不会挂载

**Comment by fanxinghaoyue0** [comment]
> 确实，这是一个问题。目前比较好的办法是在宿主机新建一个配置文件，然后把这个配置文件挂载到容器里去。 配置文件内容参考https://github.com/saltbo/zpan/blob/master/deployments/zpan.yml

我用另一台vps装成功了，但是控制台输出的密码输入后提示错误，这个用户名密码有方法重置吗

**Comment by saltbo** [comment]
密码错误？ 你是不是复制粘贴的 有空格？ 好像是没有处理空白字符。 目前还不能修改账号密码，用户系统部分后续会补上的。如果还不行可以把数据库文件删了重新启动zpan

**Comment by saltbo** [comment]
docker 挂载就是在docker run的时候加上-v 参数 你可以搜一下 很简单

**Comment by saltbo** [comment]
v1.5.5版本发布了，现在我们做了可视化安装页面，安装的时候会自动创建config.yml文件。默认安装目录是/etc/zpan，所以直接-v /etc/zpan:/etc/zpan就可以把配置文件挂载出来进行修改了，欢迎使用~
