### ISSUE TITLE
请问初始用户是什么？或者怎么注册？

### ISSUE THREAD

**Issue by te3** [saltbo/zpan#53]
如题

**Comment by saltbo** [comment]
在启动日志里

**Comment by MisterWenLai** [comment]
> 在启动日志里

能具体说一下吗？我在boot.log里没看到任何相关字段……

**Comment by saltbo** [comment]
> > 在启动日志里
> 
> 能具体说一下吗？我在boot.log里没看到任何相关字段……

boot.log是什么？ zpan的日志是输出在stdout里， 如果是docker启动可以去docker logs里查看

**Comment by te3** [comment]
> 在启动日志里
谢谢，找到了。怎么添加新用户来着？

**Comment by saltbo** [comment]
目前只能让用户自己注册，管理员添加用户功能后续会上

**Comment by te3** [comment]
> 目前只能让用户自己注册，管理员添加用户功能后续会上

注册时邀请码怎么填？

**Comment by saltbo** [comment]
https://zpan.space/#/zh-cn/config?id=invitation

注册邀请默认是关闭的，所以不用填就可以注册了。如果开启了则必须填邀请码

**Comment by MisterWenLai** [comment]
> > > 在启动日志里
> > 
> > 
> > 能具体说一下吗？我在boot.log里没看到任何相关字段……
> 
> boot.log是什么？ zpan的日志是输出在stdout里， 如果是docker启动可以去docker logs里查看

是/dev/stdout吗？这个里面是空白的，什么都没有。

**Comment by saltbo** [comment]
你得先确定你是怎么启动的

**Comment by MisterWenLai** [comment]
> 你得先确定你是怎么启动的

CentOS 8，systemctl启动的

**Comment by saltbo** [comment]
`journalctl -u`

https://zpan.space/#/zh-cn/faq

**Comment by saltbo** [comment]
从v1.5开始增加了可视化安装引导页面，可以自行创建管理员账户密码
