### ISSUE TITLE
腾讯云COS，如何配置Provider？不成功

### ISSUE THREAD

**Issue by zlyuan99** [saltbo/zpan#58]
配置文件放在/data/zpan/conf 用docker 启动好像不行

配置文件如下：
![image](https://user-images.githubusercontent.com/30078049/99473605-d839fc00-2985-11eb-860d-22a769966b52.png)

Docker启动方式如下：
 docker run -p 8081:8222 -v /data/zpan/data:/zpan -v /data/zpan/conf:/etc/zpan -it saltbo/zpan:latest
启动报错

Using config file: /etc/zpan/zpan.yml
WARN[0000] grbac abandoned the periodic loader because loadInterval is less than 0
WARN[0000] grbac abandoned the periodic loader because loadInterval is less than 0

![image](https://user-images.githubusercontent.com/30078049/99473706-12a39900-2986-11eb-8a33-c716b0dc0151.png)
貌似提示有问题，大佬指导一下，
另外，看不到后台管理帐号密码怎么办？

**Comment by saltbo** [comment]
这个warn不用管它， 但是确实很奇怪为啥没有提示账号密码呢？ 

你删了镜像重新run下呢

**Comment by zlyuan99** [comment]
重命名 zpan.db 后再次启动Docker 有出现用户名和密码了
![image](https://user-images.githubusercontent.com/30078049/99504204-29fc7980-29ba-11eb-8ba4-25c836cb5c04.png)
但是上传文件还是失败
应该是 provider 配置有问题
![image](https://user-images.githubusercontent.com/30078049/99504319-56b09100-29ba-11eb-98a1-688af9513a08.png)
一直这样，没反应

**Comment by saltbo** [comment]
需要上腾讯云做跨域配置

**Comment by saltbo** [comment]
v1.5.5版本已发布，支持管理后台添加配置云存储，可以再试试
