### ISSUE TITLE
set quota for the num of files in the folders

### ISSUE THREAD

**Issue by saltbo** [saltbo/zpan#6]

**Comment by XiangYu0777** [comment]
Received.

**Comment by XiangYu0777** [comment]
@saltbo How much quota is proper ??

**Comment by saltbo** [comment]
> FAT
512 Files Per Folder

> FAT32
65,534 Files Per Folder

> NTFS
4,294,967,295 Files Per Folder

> Ext3 
31,998 Files Per Folder

> Ext4
64,998 Files Per Folder

**Comment by XiangYu0777** [comment]
clear.
