### ISSUE TITLE
腾讯云COS无法清空回收站

### ISSUE THREAD

**Issue by mc7qing** [saltbo/zpan#60]
![image](https://user-images.githubusercontent.com/33148552/100186127-5bc49180-2f20-11eb-95a8-65cef49df91c.png)

RT 上传和下载测试了一下没有啥问题

然后分享也有问题

![image](https://user-images.githubusercontent.com/33148552/100186505-1ce30b80-2f21-11eb-969e-ff00fe19db53.png)

**Comment by mc7qing** [comment]
但是看到演示站好像没有这些问题 是不是docker的镜像还没更新呢？ 还是只有腾讯云COS会这样呢

**Comment by mc7qing** [comment]
![image](https://user-images.githubusercontent.com/33148552/100196836-6a1ca880-2f34-11eb-9ba4-97eaec73da51.png)
重新安装了最新版本  上面的问题都没了  但是回收站删除空文件夹还是有问题的~

**Comment by mc7qing** [comment]
![image](https://user-images.githubusercontent.com/33148552/100198020-33e02880-2f36-11eb-97a0-de7cf119d366.png)
后台管理报错

**Comment by saltbo** [comment]
v1.5.5版本已发布，管理后台基本完善，可以再试试
