### ISSUE TITLE
部署后文件夹中文件不显示

### ISSUE THREAD

**Issue by deepinsea** [saltbo/zpan#61]
部署后可以存储（数据库中有）和创建文件夹，但是"全部文件"中不显示是什么原因？还有windows可以本地调试吗？怎么调试？

**Comment by saltbo** [comment]
这种情况是没有上传成功的。应该是没有设置跨域，需要到云存储控制台进行设置。跨域参数详见zpan.space文档

**Comment by saltbo** [comment]
v1.5.5版本，目前常用云存储已支持自动设置CORS。
