### ISSUE TITLE
Does Zpan support ceph s3 storage?

### ISSUE THREAD

**Issue by zh23jemu** [saltbo/zpan#65]
Hi, I have a local ceph object storage.
I edited config file as below but it seems it does not work.
I replaced endpoint info with ip:port and have already created the bucket.

provider:
  name: s3
  bucket: test01
  endpoint: http://ip:port
  accessKey: NA84AFWMLZWGAOQW5WKX
  accessSecret: qxiiY86XaLPU7jocqOsi26m8EjmShQdwxj4budVw

**Comment by saltbo** [comment]
I have't try to use the ceph object storage,But as long as the theory that supports the S3 protocol can be used.

And the endpoint can't be `ip:port` because of the [VirtualHosting](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html)

**Comment by saltbo** [comment]
use s3 for it
