### ISSUE TITLE
能以原始文件名存储么？

### ISSUE THREAD

**Issue by slitilanber** [saltbo/zpan#66]
上传到bucket里的文件名变得毫无意义，这个应用又不是定位为企业，个人私有云，希望能以原始文件名存储

**Comment by saltbo** [comment]
不好意思，bucket里不存储文件名是因为当初设计的时候我觉得重命名或者移动的时候还得去改bucket里的文件名和路径，比较麻烦。所以采用了这种方案。

另外，说明一下，我们的定位并不只是网盘，是希望为企业服务的。

**Comment by saltbo** [comment]
从v1.5开始，可以通过环境变量进行配置，比如$RAW_PATH/$RAW_NAME
