### ISSUE TITLE
上传文件到七牛云报错

### ISSUE THREAD

**Issue by HuanYuanHe** [saltbo/zpan#68]
![image](https://user-images.githubusercontent.com/51042672/103632345-1ebbd800-4f7f-11eb-9301-37d8fb1cb723.png)
请问这个报错该怎么解决呢，好像是证书相关的报错

我的配置文件是这样的
![image](https://user-images.githubusercontent.com/51042672/103632448-4743d200-4f7f-11eb-80cf-e721369594ba.png)

**Comment by saltbo** [comment]
七牛有一个s3专用的域名 可以在控制台找下

**Comment by HuanYuanHe** [comment]
今早配了华南地区域名http://upload-z2.qiniup.com和customHost（云存储绑定的自定义域名） 可以上传了 ，感觉配置文件可以提示一下哪些字段是必填的。 
现在有个问题只能传小图片，传个10M的文档也会报错，哪里可以配置上传文件大小的限制吗
![image](https://user-images.githubusercontent.com/51042672/103719805-cf1fef80-5004-11eb-8c61-aefe5de938e2.png)

**Comment by saltbo** [comment]
这域名还不对

**Comment by HuanYuanHe** [comment]
![image](https://user-images.githubusercontent.com/51042672/103721380-78b4b000-5008-11eb-8136-6983a9a992f9.png)
我是参照这个填的 ，图片几十K的那种可以上传，所以域名应该是没问题了。但是大文件就传不了了是什么情况呢

**Comment by saltbo** [comment]
不是这个 去控制台找

**Comment by HuanYuanHe** [comment]
![image](https://user-images.githubusercontent.com/51042672/103722148-4d32c500-500a-11eb-9c6a-959ee4480257.png)
customHost我用的这个自定义域名

**Comment by HuanYuanHe** [comment]
七牛云没有明确给出endpoint地址，改了大半天，改用阿里云后可以正常上传了

**Comment by saltbo** [comment]
![image](https://user-images.githubusercontent.com/17308208/103751011-96067000-5042-11eb-854f-56b0d561f40a.png)
