### ISSUE TITLE
如何查看错误日志？

### ISSUE THREAD

**Issue by blankwz** [saltbo/zpan#71]
已经部署完成，但是上传无任何反应，不知道哪里出现问题，如何查看错误日志？
用的COS，跨越也设置了，其他都按教程设置。不知道哪里出现问题
配置如下：
server:
  port: 8222
  sslport: 443
  domain:
   - ww.kan.lol

database:
  driver: mysql
  dsn: TencentCOS:TDASBy83YijC2BiL@tcp(127.0.0.1:3306)/TencentCOS?charset=utf8&parseTime=True&loc=Local

provider:
  name: s3
  bucket: pan-122312112
  endpoint: https://cos.ap-nanjing.myqcloud.com
  accessKey: AKIDSnuxxxxxxxxxAfTUwRnn3bL
  accessSecret: e6JL8hgxxxxx7UenOG

**Comment by saltbo** [comment]
目前有一些接口报错没有弹出来，需要打开浏览器开发者工具看下报啥错了

**Comment by blankwz** [comment]
谢谢
