### ISSUE TITLE
如何删除或者更新zpan？

### ISSUE THREAD

**Issue by blankwz** [saltbo/zpan#77]
想要更新到1.55，不知道如何更新，怕覆盖安装出错，
就想到删除服务，也不太会删除服务
用下面的方法删除，然后重装，无效（我是Linux小白）
`systemctl disable zpan.service   # 禁止自启动
systemctl stop zpan  # 停止

rm -rf /etc/systemd/system/zpan.service
rm -rf /etc/zpan`

现在是完全没有用了。
另外，如果重装，只要配置到原来的数据库，里面的对象存储关系信息列表应该都在的吧

**Comment by saltbo** [comment]
v1.5对数据库有改动，但是目前没有自动升级策略。

其实只需要把数据库备份一下，然后覆盖安装就好了。安装好之后再把数据导回去。

导入的时候需要注意
1. matter表、share表、recycle表新增了sid，也就是storage表的主键id。
2. matter表的dirtype>0的数据需要把uploaded_at设置一个时间，否则会不显示文件夹

**Comment by blankwz** [comment]
感谢!
