### ISSUE TITLE
【bug】文件上传中断后仍然会占用存储容量。

### ISSUE THREAD

**Issue by Hope-you** [saltbo/zpan#78]
![image](https://user-images.githubusercontent.com/34697553/108813465-07e34a80-75ec-11eb-837e-5723926c677f.png)

**Comment by CharlesYe8848** [comment]
我也是

**Comment by saltbo** [comment]
v1.6改成实际上传完再计算使用量了。但是这样一来，在同时上传几个大文件的时候会出现超出允许的存储空间的情况。

这个问题将来参考某度的做法，上传时进行排队，不允许并发上传。

**Comment by saltbo** [comment]
#16  重构上传对话框时实现
