### ISSUE TITLE
请问发信邮箱如何设置

### ISSUE THREAD

**Issue by Hang-shao** [saltbo/zpan#80]
![image](https://user-images.githubusercontent.com/50350694/109017194-ea000d80-76f1-11eb-877e-a056fb069bc4.png)

**Comment by saltbo** [comment]
就是需要弄一个发信邮箱，我用的阿里云的邮件推送。弄个二级域名配置下，把账户名密码弄过来就行了

https://dm.console.aliyun.com/

**Comment by Hang-shao** [comment]
设置一下，好像还有问题，请指教🙏发自我的荣耀手机-------- 原始邮件 --------发件人： Ambor <notifications@github.com>日期： 2021年2月25日周四 09:56收件人： saltbo/zpan <zpan@noreply.github.com>抄送： Pamhub <mir_soh@163.com>, Author <author@noreply.github.com>主    题： Re: [saltbo/zpan] 请问发信邮箱如何设置 (#80)

就是需要弄一个发信邮箱，我用的阿里云的邮件推送。弄个二级域名配置下，把账户名密码弄过来就行了

https://dm.console.aliyun.com/

**Comment by saltbo** [comment]
报啥错了 配置发一下

**Comment by recdown** [comment]
> 报啥错了配置发一下

![image](https://user-images.githubusercontent.com/44447180/121792244-0bdfba80-cc25-11eb-80c9-0ceed664d708.png)
企业微信邮箱实测无法使用

**Comment by saltbo** [comment]
这个是说密码必填
