### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by fcwys** [saltbo/zpan#82]
希望分享增加永久分享，此外移动端布局几乎没法用，希望适配，现在移动端使用挺多的，谢谢！

**Comment by saltbo** [comment]
嗯嗯，目前缺少永久分享和取消分享。

移动端适配工作量比较大，希望有前端大拿能支持下

**Comment by swuecho** [comment]
移动端直接弄个app 最好，哈哈。

客户端功能可以少一点。

**Comment by saltbo** [comment]
> 移动端直接弄个app 最好，哈哈。
> 
> 客户端功能可以少一点。

也可以 奈何客户端开发经验很少 个人时间有限。。

**Comment by saltbo** [comment]
永久分享已支持，v1.6可用

**Comment by saltbo** [comment]
移动端适配可见 #28
