### ISSUE TITLE
通过docker启动失败

### ISSUE THREAD

**Issue by ekesaiting** [saltbo/zpan#83]
启动日志
`` is not officially supported, running under compatibility mode.
2021/02/25 03:32:52 sql: unknown driver "" (forgotten import?)

**Comment by saltbo** [comment]
是latest版本吗，看下hash是多少，最新的是b3846ebee1fbfcc70f5edb34dfe3378f0b89d45702a4232107c5f40375935c19

如果不是的话，是否使用了什么mirror？国内的mirror好像都有缓存

**Comment by ekesaiting** [comment]
是阿里云镜像的问题，换官方源就好了
