### ISSUE TITLE
接入点希望可以下拉框选择

### ISSUE THREAD

**Issue by fcwys** [saltbo/zpan#84]

**Comment by saltbo** [comment]
接入点各大厂商都没有提供相关API可以使用。但是我有一个想法，可以维护一个接入点的Git仓库，zpan可以从这个仓库里拉取endpoint列表

**Comment by saltbo** [comment]
https://github.com/eplist/eplist

模仿gfw建立了一个eplist，希望通过社区来维护这个列表。等收录的云存储平台基本完善后ZPan会接入使用它

**Comment by zmoon460** [comment]
这个主意很赞，接入list后，使用上肯定方便很多

**Comment by saltbo** [comment]
v1.6即将启用eplist，欢迎有需要的人去贡献PR
