### ISSUE TITLE
window本地怎么运行该服务

### ISSUE THREAD

**Issue by DyncKathline** [saltbo/zpan#86]
目前使用go run main.go不行

**Comment by saltbo** [comment]
需要cgo，应该需要安装相关的依赖

**Comment by DyncKathline** [comment]
> 需要cgo，应该需要安装相关的依赖

能提供具体代码吗，目前看到演示网站，界面和功能是我想要的，目前苦于本地运行不了，希望能提供一下

**Comment by saltbo** [comment]
zpan是一个服务端程序，所以我们没有优先考虑在Windows上运行。可以使用heroku一键部署进行体验，或者使用docker进行体验。然后在Linux服务器上进行安装

**Comment by saltbo** [comment]
#70
