### ISSUE TITLE
使用minio,无法上传文件，显示网络错误

### ISSUE THREAD

**Issue by molin2050** [saltbo/zpan#93]
![image](https://user-images.githubusercontent.com/14227424/110572090-b6ae8b80-8193-11eb-8ca3-cd422c1a16cf.png)

**Comment by saltbo** [comment]
https://github.com/saltbo/zpan/issues/57#issuecomment-728649667

参考这里配置，然后做泛解析。我看你的liujiqing.www.jiqingzhineng.com都不通

**Comment by molin2050** [comment]
你说的不通是你试了还是看了哪里啊。我是看57照做的啊

**Comment by saltbo** [comment]
我试了。 #57 里用的是localhost 不需要解析 你自己的域名需要做泛解析

**Comment by molin2050** [comment]
这个bucket 名称加在了域名的前面是正常的吧，我也可以用localhost

**Comment by molin2050** [comment]
反馈挺快的，之前用了阿里云oss ,速度起飞，关键是要前，我又是资料狂魔。所以oss不适合

**Comment by molin2050** [comment]
你最好创建个qq或者微信群，有问题都好沟通

**Comment by molin2050** [comment]
又折腾了一会，云服务配置了子域名解析也不行，本地配置也没错成功，从入门到放弃了。有没有手把手教程啊

**Comment by saltbo** [comment]
官网有微信群你没注意，直接搜我用户名也能找到

**Comment by molin2050** [comment]
二维码已过期

**Comment by molin2050** [comment]
minio 能不能出个教程呢

**Comment by molin2050** [comment]
zpan 啥时候支持本地物理存储，不用minio,就普通网盘功能

**Comment by saltbo** [comment]
> 二维码已过期

https://zpan.space/#/zh-cn/faq 不知道你看的哪里的二维码 这里有

**Comment by saltbo** [comment]
后面有时间会做一个，我们不会支持本地存储

**Comment by hybgithub1** [comment]
我也是照着57 做的 用的阿里云域名 怎么都没有成功。真的是从入门到放弃了。关键是操作文档就几个配置名词解释，网上找个教程都找不到。加微信群 只是入场的时候有点反应，找了一天，像是盲人摸象。累了。

**Comment by saltbo** [comment]
minio搭建的时候只要正确启用Virtual Hosted-Style模式就可以了。Virtual Hosted-Style就是bucket的名称包含在域名中。比如MINIO_DOMAIN=minio.example.com，那么你创建一个名叫zpan的bucket，这时该bucket的访问地址就是zpan.minio.example.com

这时只要保证域名解析正确，有端口的情况下保证端口对外已经开放。在公网能够正常访问zpan.minio.example.com，那么就不会有啥问题了
