### ISSUE TITLE
文件删除bug

### ISSUE THREAD

**Issue by Tangerg** [saltbo/zpan#94]
文件夹删除有bug
先删除子文件夹，然后删除他的父文件夹，然后恢复先前删除的子文件夹，这个时候在所有文件里看不到刚刚恢复的子文件夹，只有恢复了被删除的父文件夹才会显示出来

**Comment by saltbo** [comment]
🤣   确实存在这个问题。不过，我也没想好咋解决，回头我去测下某度网盘是怎么处理的。可能在恢复子文件夹的时候报错吧

**Comment by Tangerg** [comment]
> 🤣 确实存在这个问题。不过，我也没想好咋解决，回头我去测下某度网盘是怎么处理的。可能在恢复子文件夹的时候报错吧

直接在恢复的时候判断父级文件夹是否存在啊，存在就放回去，不存在就直接丢到根目录去，我看了源码的，没有这部分逻辑

**Comment by saltbo** [comment]
#184
